### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by antsmartian** [joeyhaohao/amazon_recommender#3]
Wondering how I can start up this project?

**Comment by joeyhaohao** [comment]
Hi @antsmartian , please see the `Getting Start` in README.

**Comment by antsmartian** [comment]
Thanks @joeyhaohao . Still I need bit clarification:

> Download the product metadata to springbackend/src/main/resources/data. Please see the data format in the next section.
> 
> Download the user rating data to recommender/src/main/resources/data. Please see the data format in the next section.

I guess for the first one we need to download `productMeta.txt.gz`. Not sure, where is the user rating data?

**Comment by joeyhaohao** [comment]
If you are using the Stanford dataset, the ratings are included in product reviews. You may check out the per-category data [here](http://snap.stanford.edu/data/amazon/)
